x-airflow-common: &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://football_user:football_pass@postgres/airflow_db
    AIRFLOW__CORE__FERNET_KEY: 'YlCMTMjFqdWxhMQCYK8YZdHXbXBnLzsBkHBijsZMhpQ='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data
    - ./.env:/opt/airflow/.env
    - ./dbt_project:/opt/airflow/dbt_project
  depends_on:
    - postgres

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: football_postgres
    environment:
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: football_pass
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: football_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@football.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin123 --firstname Football --lastname Admin --role Admin --email admin@football.com || true && airflow webserver"
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: bash -c "sleep 30 && airflow scheduler"
    restart: always
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: football_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
volumes:
  postgres_data:
